name: Generate Pacman
on:
  schedule:
  - cron: "0 */12 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate pacman graph
        uses: Platane/snk@v3
        with:
          github_user_name: AbdulWahabXVI
          outputs: |
            output/pacman-contribution-graph.svg?palette=github
